# Generated by Django 3.1.4 on 2020-12-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_sources', to='polls.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_choices', to='polls.scenario')),
                ('simulation_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_choices', to='polls.simulationsource')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='choices',
            field=models.ManyToManyField(related_name='scenarios', through='polls.ScenarioChoice', to='polls.SimulationSource'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='polls.simulation'),
        ),
    ]
