# Generated by Django 3.0.8 on 2020-07-28 12:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='choice',
            managers=[
                ('bob', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('bob', django.db.models.manager.Manager()),
            ],
        ),
    ]
