# Generated by Django 3.1rc1 on 2020-07-29 07:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'base_manager_name': 'lib_manager'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'base_manager_name': 'lib_manager'},
        ),
        migrations.AlterModelManagers(
            name='choice',
            managers=[
                ('lib_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('lib_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
