# Generated by Django 3.1.4 on 2020-12-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationsource',
            name='simulation',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='choices',
        ),
        migrations.DeleteModel(
            name='ScenarioChoice',
        ),
        migrations.DeleteModel(
            name='SimulationSource',
        ),
    ]
