# Generated by Django 3.0.8 on 2020-07-28 12:19

from django.db import migrations


def test(apps, schema_editor):
    Question = apps.get_model("polls", "Question")
    print(Question.objects.all())


class Migration(migrations.Migration):
    dependencies = [("polls", "0002_auto_20200728_1314")]
    operations = [migrations.RunPython(test)]
